### PR TITLE
Updating youki logo in README

### PR DESCRIPTION
**Pull request by mairin**
This PR in the common repo needs to be merged before this PR should be accepted:
https://github.com/containers/common/pull/1409

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
LGTM, but waiting on the common PR to be be approved/merged before hitting merge on this one.

**Comment by TomSweeneyRedHat** [comment]
and I should note, LGTM, in this case translates to Looks GREAT To Me  :smiley:

**Comment by benoitf** [comment]
looks like we can merge now

**Comment by Luap99** [comment]
looks great

**Pull request merged**
