### PR TITLE
Add Podman Desktop logo

### PR DESCRIPTION
**Pull request by ashley-cui**
Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by ashley-cui** [comment]
To preview what this looks like: https://github.com/containers/.github/blob/35058c74ccbc78187704f08d2274bc6556b6021f/profile/README.md

@containers/podman-desktop-maintainers @containers/podman-maintainers PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by benoitf** [comment]
it looks like the order of the logo is not following the order of the text
```
Some of our tools include [Podman](https://github.com/containers/podman), [Podman Desktop](https://github.com/containers/podman-desktop), [Buildah](https://github.com/containers/buildah), [Skopeo](https://github.com/containers/skopeo), [conmon-rs](https://github.com/containers/conmon-rs), and [crun](https://github.com/containers/crun),
```

**Comment by TomSweeneyRedHat** [comment]
The look/feel looks great to me, but I think I'd slide the Podman Desktop icon between Podman and Buildah.

**Comment by ashley-cui** [comment]
I can change either the text or the logo order to match each other! 

Putting the Desktop icon between Podman and Buildah will make the logo list look awkward though, since the art style and text alignment is still different. Let me know which you prefer, I think the Desktop logo at the end looks better 
Screen Shot 2022-10-26 at 10 16 25 AM
Screen Shot 2022-10-26 at 10 18 27 AM

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui, thanks for working that up.  First off, I think we need to have the text and pictures line up, where ever we end up.

From a precedence standpoint, I'd prefer the desktop icon to be between the Podman and Buildah icons.

However, from a look/feel standpoint, I agree with you.  The desktop icon looks much better at the end.

Given all that, I'd lean towards keeping it at the end after all.  @benoitf does that work for you?

I put the hold on until we hear from Florent.

**Comment by benoitf** [comment]
To me the logo is not looking well compare to the others so I don't find a right place for it.
let's merge as for now there was no logo and iterate later

**Comment by TomSweeneyRedHat** [comment]
@benoitf SGTM.  @ashley-cui so I think the ordering of the text needs to be done to put the desktop at the end?  Then once we get an improved Desktop icon, we can switch the precedence in a follow up PR.

**Comment by ashley-cui** [comment]
Updated the text list, feel free to merge!

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by ashley-cui** [comment]
@TomSweeneyRedHat No bot on this repo, need to push the button :)

**Comment by TomSweeneyRedHat** [comment]
But I've been told to never touch the shiny button!   Don't let @rhatdan know I touched it!

**Pull request merged**
