### PR TITLE
Add youki

### PR DESCRIPTION
**Pull request by utam0k**
#5 
image

### CODE REVIEW

**Comment by utam0k** [comment]
Wait for merging https://github.com/containers/youki/pull/1329

**Comment by utam0k** [comment]
@rhatdan May I ask you to review it?

**Comment by rhatdan** [comment]
LGTM

**Comment by mairin** [comment]
Hi @utam0k - I posted this in the youki Discord, but:

Hi! My name is Máirín (you can call me "Mo") - I designed the logos for the other container projects. I am wondering if it would be okay if I modified the youki logo on the containers README page to align more with the other logos? (Switching the typeface to the typeface the other logos use I think would be a quick and easy way, I wanted to talk to you about the logomark design too - and there's a change I just made in a recent PR to support darkmode this logo would need.) Let me know! (Also if you have an SVG version of it that would be super helpful!) 

This is the reference PR set to support dark mode on github... the last PR (PR#7) I think would be dependent on re-adding youki to the PR commits so it would be good to get the font and darkmode fixes together for it before merging:

https://github.com/containers/common/pull/1228
https://github.com/containers/.github/pull/7

**Comment by utam0k** [comment]
:wave: Hi, @mairin. I sent you a new message on Discord. May I ask you to check it?

**Pull request merged**
